Check for NFD app at the startup
named-data-mobile/ndn-photo-app pull request #126
Opened 2019-03-14 22:33 UTC by AshwinChandlapur

Check if NDN Forwarding Daemon is installed.
If installed -> Continue Regular Onboarding
If not installed -> Show a Toast Message and request User to install NDN

2019-03-15 17:14 UTC, agawande commented on app/src/main/java/memphis/myapplication/IntroActivity.java
> +        if(isPackageInstalled(nfdAppPackageName,pm))
Spacing around if:
if (isPackageInstalled(nfdAppPackageName,pm)) {

2019-03-15 17:15 UTC, agawande commented on app/src/main/java/memphis/myapplication/IntroActivity.java
> +        }else{
Spacing:
} else {

2019-03-15 17:15 UTC, agawande commented on app/src/main/java/memphis/myapplication/IntroActivity.java
> +            Toast.makeText(context,"Please consider Installing NFD, this is " +
Maybe just "Please install NFD which is required for npChat to work. Start the NFD from within the NFD app and then reopen this app." Also space after comma: context, "..."

2019-03-15 17:17 UTC, agawande commented on app/src/main/java/memphis/myapplication/IntroActivity.java
> +    final String nfdAppPackageName = "net.named_data.nfd";
Should this go in xml?

2019-03-15 17:18 UTC, agawande requested changes
We should also check if NFD is running? (Or actually that might be done by having a try-catch around face/face.processEvents - need to check what happens when application is started w/o NFD).

2019-03-15 19:13 UTC, AshwinChandlapur commented
> We should also check if NFD is running? (Or actually that might be done by having a try-catch around face/face.processEvents - need to check what happens when application is started w/o NFD).

One way to Solve This->
0. Have a method that returns defaultIdName in Globals.
`public static Name getDefaultIdName() { return defaultIdName; }`

1. Have a onResume method in MainActivity. onResume is used because, when application is re-opened from stack, we need to check for NFD status.
` @Override`
   ` protected void onResume() {`
        `super.onResume();`
       ` try {`
            `register_with_NFD(Globals.getDefaultIdName());`
       ` } catch (Exception e){`
            `e.printStackTrace();`
        `}`
    `}`

2. Modify register_with_NFD method to launch intent to NFD app when onRegisterFailure is triggered. Add the following in onRegisterFailure.
`Intent launchIntent = getPackageManager().getLaunchIntentForPackage(getString(R.string.nfd_package));`
                           ` if (launchIntent != null) {`
                                `Toast.makeText(getApplicationContext(), "Please Start NFD.",
                                        Toast.LENGTH_LONG).show();`
                                `startActivity(launchIntent); }`
                            `finish();`


If this one is an acceptable solution, I will add this code and submit a PR.

2019-03-15 19:29 UTC, agawande commented
Hmm, solution seems okay - have you tested it?

2019-03-15 19:41 UTC, AshwinChandlapur commented
I have tested with Moto-g6Play and OnePlus 3. Also, it is better if we move request for media permissions to onResume method. If it is in onCreate, then the UI will be messed up for this scenario
1. User Installs the npChat app(given NFD is already installed but not running).
2. User goes to loginActivity. Clicks on register after filling details.
3. Since, NFD is not running, onRegistrationFailure is triggered and user is taken to NFD app and also at the same time the permissions are requested.
This kinda messes UI.

2019-03-15 19:43 UTC, agawande commented
Okay, moving media permission should be fine.

2019-03-15 20:05 UTC, AshwinChandlapur commented
I have added one more commit with the discussed changes. Should be able to merge :).

2019-03-18 17:18 UTC, jrandallclark commented
@AshwinChandlapur Everything looks good. Could you please fix the conflicts caused by some of the other pull requests that have been merged?

2019-03-18 17:41 UTC, AshwinChandlapur commented
Hey @jrandallclark, 
I tried fixing the conflicts and running the app. I ran into 
`Attempt to invoke virtual method 'net.named_data.jndn.util.MemoryContentCache memphis.myapplication.MemoryCache.getmCache()' on a null object reference`

In the method register_with_NFD, Globals.memoryCache.getmCache() is throwing null pointer. Also, in Globals setMemoryCache is unused.

2019-03-18 17:55 UTC, AshwinChandlapur commented
Yup @jrandallclark . I have resolved conflicts. I guess, the branch is ready to be merged.

2019-03-20 00:23 UTC, somenath1435 commented
@AshwinChandlapur squash commits

2019-03-20 16:35 UTC, merged

2019-03-22 20:31 UTC, jrandallclark commented
@AshwinChandlapur It turns out that calling register_with_NFD within MainActivity's OnResume isn't a good idea as it causes the app to re-register with NFD every time the user sees the main activity. I've reverted your pr for now.

2019-03-22 20:46 UTC, AshwinChandlapur commented
To fix this, we can have register_NFD method in onCreate and Permissions in onResume. I guess, that would fix this problem of re-registering.

2019-03-22 21:26 UTC, AshwinChandlapur commented
The registerNFD method was put in onResume because of scenarios such as this
1. Log into the app with NFD status running.
2. While using the app, if user decides to clear the background apps then NFD app would be closed and app wouldn't inform user about the NFD.