solve issue #78
named-data-mobile/ndn-photo-app pull request #171
Opened 2020-01-12 14:16 UTC by amit6663

![Screenshot_20200112-194413](https://user-images.githubusercontent.com/45551012/72220188-329f4a80-3574-11ea-8421-872ceda09ded.png)
**Description (required)**

Fixes #{GitHub issue number} {Github issue title}

What changes did you make and why?

**Tests performed (required)**

Tested {build variant, e.g. ProdDebug} on {name of device or emulator} with API level {API level}.

**Screenshots showing what changed (optional - for UI changes)**

---

_Note: Please ensure that you have read CONTRIBUTING.md if this is your first pull request._

2020-01-12 14:25 UTC, amit6663 commented
@jrandallclark  can i make a slack channel for this community and share link with you?

2020-01-13 21:12 UTC, jrandallclark requested changes
Does this button rotate the photo 90 degrees each time you press it?

> @jrandallclark can i make a slack channel for this community and share link with you?

Our organizational Slack channel will open up soon.

2020-01-13 21:12 UTC, jrandallclark commented on app/src/main/java/memphis/myapplication/UI/SettingsFragment.java
> +               //             .into(m_imageView);
Remove any commented out code.

2020-01-13 21:12 UTC, jrandallclark commented on app/src/main/java/memphis/myapplication/UI/SettingsFragment.java
> +         int rotation = getRotation(context, selectedImage);
Fix indentation.

2020-01-13 21:12 UTC, jrandallclark commented on app/src/main/java/memphis/myapplication/UI/SettingsFragment.java
> +            while(mediaCursor.moveToNext()){
Space after "while".

2020-01-13 21:12 UTC, jrandallclark commented on app/build.gradle
> +
Nothing was added here. Remove build.gradle from your commit.

2020-01-14 04:17 UTC, amit6663 commented
@jrandallclark yeah, i fixed

2020-01-14 19:42 UTC, jrandallclark commented
I don't think we want users to rotate their profile pictures within the app. The bug here is that the profile photo is sometimes displayed incorrectly regardless of the correct orientation of the photo. If a user wants to change the orientation, they should rotate it in an image editor and re-upload it to the app. The app should then display the photo correctly.

2020-08-24 17:57 UTC, closed without merging